name: lapce # you probably want to 'snapcraft register <name>'
adopt-info: lapce
base: core20 # the base snap is the execution environment for this snap
summary: Lightning-fast and Powerful Code Editor written in Rust! # 79 char long summary
description: |
  Lapce is a fast and powerful code editor written in Rust which supports
  plugins, remote development, a built in terminal and more!

  (this unoffical snap package is not from the authors of Lapce)
title: Lapce
icon: logo.png
website: https://lapce.dev
source-code: https://github.com/lapce/lapce.git
issues: https://github.com/lapce/lapce/issues
license: Apache-2.0

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: arm64
    run-on: arm64

apps:
  lapce:
    command: bin/lapce
    extensions: [kde-neon]
    plugs:
      - home
      - opengl
      - x11
      - network

parts:
  lapce:
    source: https://github.com/lapce/lapce.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    plugin: rust
    build-packages:
      - squid-deb-proxy-client
      - libjsoncpp1
      - libarchive13
      - libuv1
      - librhash0
      - pkgconf
      - librust-expat-sys-dev
      - libfreetype-dev
      - fontconfig
      - libfontconfig1
      - libfontconfig1-dev
      - libxcb-render-util0
      - libxcb-render-util0-dev
      - libxcb-render0
      - libxcb-render0-dev
      - libxcb-shape0
      - libxcb-shape0-dev
      - libxcb-xfixes0
      - libxcb-xfixes0-dev
      - libxcb-xkb-dev
      - libxcb-xkb1
      - libxkbcommon0
      - libxkbcommon-x11-dev
      - libxkbcommon-dev
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libxcb1
      - libx11-6
      - libx11-xcb1
      - libxcursor-dev
      - libxrandr2
      - libxi6
      - ibus-gtk
      - libibus-1.0-5
