name: lapce # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.0.12+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Lightning-fast and Powerful Code Editor written in Rust! # 79 char long summary
description: |
  Lapce is a fast and powerful code editor written in Rust which supports
  plugins, remote development, a built in terminal and more!

  (this unoffical snap package is not from the authors of Lapce)
title: Lapce
website: https://lapce.dev
source-code: https://github.com/lapce/lapce.git
issues: https://github.com/lapce/lapce/issues

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  lapce:
    command: target/release/lapce

parts:
  lapce:
    source: https://github.com/lapce/lapce.git
    source-type: git
    override-pull: snapcraftctl pull && sudo apt-get install pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev
    plugin: rust
    build-packages: [cmake]
