name: lapce # you probably want to 'snapcraft register <name>'
adopt-info: lapce
base: core18 # the base snap is the execution environment for this snap
summary: Lightning-fast and Powerful Code Editor written in Rust! # 79 char long summary
description: |
  Lapce is a fast and powerful code editor written in Rust which supports
  plugins, remote development, a built in terminal and more!

  (this unoffical snap package is not from the authors of Lapce)
title: Lapce
icon: logo.png
website: https://lapce.dev
source-code: https://github.com/lapce/lapce.git
issues: https://github.com/lapce/lapce/issues
license: Apache-2.0

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: arm64
    run-on: arm64

  - build-on: i386
    run-on: i386

apps:
  lapce:
    command: bin/lapce
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa-gl:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xorg:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - cups-control
      - gsettings
      - home

parts:
  lapce:
    source: https://github.com/lapce/lapce.git
    source-type: git
    override-pull: |
      git clone https://github.com/lapce/lapce.git /root/parts/lapce/src/
      /root/.cargo/bin/cargo +stable fetch --manifest-path /root/parts/lapce/src/Cargo.toml
      snapcraftctl set-version "$(git describe --tags)"
      sudo apt-get install -y pkg-config
    plugin: rust
    build-packages:
      - cmake
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libpng16-16
      - libxau6
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxkbcommon0
      - libx11-6
      - libx11-xcb1
      - libxcursor1
      - libxrandr2
      - libxi6
