name: lapce # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Lightning-fast and Powerful Code Editor written in Rust! # 79 char long summary
description: |
  Lapce is a fast and powerful code editor written in Rust which supports
  plugins, remote development, a built in terminal and more!

  (this unoffical snap package is not from the authors of Lapce)
title: Lapce
icon: logo.png
website: https://lapce.dev
source-code: https://github.com/lapce/lapce.git
issues: https://github.com/lapce/lapce/issues
license: Apache-2.0

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  lapce:
    command: bin/lapce

parts:
  lapce:
    source: https://github.com/lapce/lapce.git
    source-type: git
    override-pull: snapcraftctl pull && sudo apt-get install -y pkg-config
    plugin: rust
    build-packages:
      - cmake
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libpng16-16
      - libxau6
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxkbcommon0
